#include "unity/unity.h"

/* Declare test functions */
void test_pmm_init_alloc_free_count(void);
void test_pmm_reserve_range(void);
void test_kheap_basic_alloc_free(void);
void test_vmm_map_translate_unmap_page(void);
void test_vmm_map_range_and_unmap_range(void);
void test_vmm_user_exec_mapping_flags(void);
void test_vmm_kernel_mapping_can_be_replaced_with_user_mapping(void);
void test_process_user_range_contains_registered_regions(void);
void test_process_remove_user_region_exact_match(void);
void test_process_user_region_mapping_metadata_round_trips(void);
void test_process_alloc_user_region_bumps_page_aligned_arena(void);
void test_process_alloc_user_region_respects_region_limit(void);
void test_process_current_and_region_limits(void);
void test_process_entry_page_table_and_exit_state(void);
void test_process_save_context_copies_registers_and_trap_state(void);
void test_process_load_context_writes_exception_frame(void);
void test_process_table_alloc_release_and_limits(void);
void test_process_next_runnable_round_robin_and_reclaim_zombies(void);
void test_user_image_entry_uses_base_plus_offset(void);
void test_user_image_prepare_process_registers_image_and_stack(void);
void test_user_image_load_copy_copies_source_and_sets_descriptor(void);
void test_user_image_load_flat_uses_header_entry_table(void);
void test_user_image_prepare_process_rejects_invalid_inputs(void);
void test_user_image_load_copy_rejects_invalid_ranges(void);
void test_user_image_load_flat_rejects_invalid_headers(void);
void test_user_vm_map_anonymous_installs_user_pte(void);
void test_user_vm_unmap_anonymous_removes_pte_and_frees_pages(void);
void test_user_vm_rejects_invalid_inputs_without_regions(void);
void test_user_vm_map_physical_maps_registered_region(void);
void test_user_vm_map_physical_rejects_unregistered_region(void);
void test_user_vm_physical_mappings_stay_per_process(void);
void test_fb_init_rejects_invalid_geometry(void);
void test_fb_putpixel_and_fillrect_clip_to_bounds(void);
void test_fb_blit_copies_and_clips_source_pixels(void);
void test_dtb_get_framebuffer_reads_simple_framebuffer(void);
void test_dtb_get_framebuffer_rejects_incomplete_node(void);
void test_virtio_blk_probe_reads_capacity(void);
void test_virtio_blk_probe_rejects_non_block_device(void);
void test_virtio_blk_probe_range_finds_later_transport(void);
void test_virtio_blk_init_programs_modern_queue(void);

int main(void) {
    UNITY_BEGIN();

    RUN_TEST(test_pmm_init_alloc_free_count);
    RUN_TEST(test_pmm_reserve_range);
    RUN_TEST(test_kheap_basic_alloc_free);
    RUN_TEST(test_vmm_map_translate_unmap_page);
    RUN_TEST(test_vmm_map_range_and_unmap_range);
    RUN_TEST(test_vmm_user_exec_mapping_flags);
    RUN_TEST(test_vmm_kernel_mapping_can_be_replaced_with_user_mapping);
    RUN_TEST(test_process_user_range_contains_registered_regions);
    RUN_TEST(test_process_remove_user_region_exact_match);
    RUN_TEST(test_process_user_region_mapping_metadata_round_trips);
    RUN_TEST(test_process_alloc_user_region_bumps_page_aligned_arena);
    RUN_TEST(test_process_alloc_user_region_respects_region_limit);
    RUN_TEST(test_process_current_and_region_limits);
    RUN_TEST(test_process_entry_page_table_and_exit_state);
    RUN_TEST(test_process_save_context_copies_registers_and_trap_state);
    RUN_TEST(test_process_load_context_writes_exception_frame);
    RUN_TEST(test_process_table_alloc_release_and_limits);
    RUN_TEST(test_process_next_runnable_round_robin_and_reclaim_zombies);
    RUN_TEST(test_user_image_entry_uses_base_plus_offset);
    RUN_TEST(test_user_image_prepare_process_registers_image_and_stack);
    RUN_TEST(test_user_image_load_copy_copies_source_and_sets_descriptor);
    RUN_TEST(test_user_image_load_flat_uses_header_entry_table);
    RUN_TEST(test_user_image_prepare_process_rejects_invalid_inputs);
    RUN_TEST(test_user_image_load_copy_rejects_invalid_ranges);
    RUN_TEST(test_user_image_load_flat_rejects_invalid_headers);
    RUN_TEST(test_user_vm_map_anonymous_installs_user_pte);
    RUN_TEST(test_user_vm_unmap_anonymous_removes_pte_and_frees_pages);
    RUN_TEST(test_user_vm_rejects_invalid_inputs_without_regions);
    RUN_TEST(test_user_vm_map_physical_maps_registered_region);
    RUN_TEST(test_user_vm_map_physical_rejects_unregistered_region);
    RUN_TEST(test_user_vm_physical_mappings_stay_per_process);
    RUN_TEST(test_fb_init_rejects_invalid_geometry);
    RUN_TEST(test_fb_putpixel_and_fillrect_clip_to_bounds);
    RUN_TEST(test_fb_blit_copies_and_clips_source_pixels);
    RUN_TEST(test_dtb_get_framebuffer_reads_simple_framebuffer);
    RUN_TEST(test_dtb_get_framebuffer_rejects_incomplete_node);
    RUN_TEST(test_virtio_blk_probe_reads_capacity);
    RUN_TEST(test_virtio_blk_probe_rejects_non_block_device);
    RUN_TEST(test_virtio_blk_probe_range_finds_later_transport);
    RUN_TEST(test_virtio_blk_init_programs_modern_queue);

    return UNITY_END();
}
