#ifndef ARMONIOS_KERNEL_USER_EXIT_H
#define ARMONIOS_KERNEL_USER_EXIT_H

#include "include/armonios/abi/process.h"

/*
 * Compatibility names for observable EL0 exit codes generated by the kernel.
 * The public source of truth lives in include/armonios/abi/process.h.
 */
#define KERNEL_USER_KILL_EXIT_CODE  ARM_PROCESS_EXIT_KILLED
#define KERNEL_USER_FAULT_EXIT_CODE ARM_PROCESS_EXIT_FAULT

#endif
